要学习深度学习，⾸先需要先掌握⼀些基本技能。所有机器学习⽅法都涉及从数据中提取信息。
- 机器学习通常需要处理⼤型数据集。**线性代数**为我们提供了⼀些⽤来处理表格数据的⽅法。我们不会太深究细节，⽽是将重点放在矩阵运算的基本原理及其实现上。
- 深度学习是关于优化的学习。对于⼀个带有参数的模型，我们想要找到其中能拟合数据的最好模型。在算法的每个步骤中，决定以何种⽅式调整参数需要⼀点**微积分**知识。
- 机器学习还涉及如何做出预测：给定我们观察到的信息，某些未知属性可能的值是多少？要在不确定的情况下进⾏严格的推断，我们需要借⽤**概率语言**

## 2.1 数据操作
- 获取数据
- 将数据读入计算机后进行处理

⾸先，我们介绍n维数组，也称为张量（tensor）。深度学习框架⼜⽐Numpy的ndarray多⼀些重要功能：⾸先，GPU很好地⽀持加速计算，⽽NumPy仅⽀持CPU计算；其次，张量类⽀持⾃动微分。这些功能使得张量类更适合深度学习。

### 2.2.1 入门
首先我们导入torch

In [ ]:
import torch

张量表示由⼀个数值组成的数组，这个数组可能有多个维度。具有⼀个轴的张量对应数学上的向量（vector）；具有两个轴的张量对应数学上的矩阵（matrix）；具有两个轴以上的张量没有特殊的数学名称。

In [ ]:
#创建行向量
x = torch.arange(12)
x

默认创建为整数。也可指定创建类型为浮点数。张量中的每个值都称为张量的元素（element）。除⾮额外指定，新的张量将存储在内存中，并采⽤基于CPU的计算。 

In [ ]:
#可以通过张量的shape属性来访问张量（沿每个轴的⻓度）的形状。
x.shape

In [ ]:
#如果只想知道张量中元素的总数，可以检查它的大小。
x.numel()

In [ ]:
#要想改变⼀个张量的形状⽽不改变元素数量和元素值，可以调⽤reshape函数。
x = x.reshape(3, 4)
x

我们不需要手动指定每个维度来改变形状。可以通过-1来调用自动计算出维度的功能。即我们可以⽤`x.reshape(-1,4)`或`x.reshape(3,-1)`来取代`x.reshape(3,4)`。

In [ ]:
#创建全零的张量
torch.zeros((2, 3, 4))

In [ ]:
#创建全一的张量
torch.ones((2, 3, 4))

In [ ]:
#创建⼀个形状为（3,4）的张量。其中的每个元素都从均值为0、标准差为1的标准⾼斯分布（正态分布）中随机采样。

torch.randn(3, 4)

tensor([[-1.1086, -0.3923, -0.8906, -0.2774],
        [ 1.1611, -0.6318,  0.1604,  0.2110],
        [ 0.4995, -0.2089,  0.2819,  0.4338]])

In [ ]:
#通过提供包含数值的Python列表，来为所需的张量中每一个元素赋予确定值
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

### 2.1.2 运算符

In [ ]:
#对于任意具有相同形状的张量，常⻅的标准算术运算符（+、-、*、/和**）都可以被升级为按元素运算。
#我们可以在同⼀形状的任意两个张量上调⽤按元素操作。
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [ ]:
#“按元素”⽅式可以应⽤更多的计算，包括像求幂这样的⼀元运算符。
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

除了按元素计算外，我们还可以执行线性代数运算，包括向量点积和矩阵乘法。

In [ ]:
#将多个张量连接到一起
x = torch.arange(12, dtype=torch.float32).reshape(3, 4)
y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((x, y), dim=0), torch.cat((x, y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [ ]:
#通过逻辑运算符构建⼆元张量。
x == y
#对于每个位置，如果X和Y在该位置相等，则新张量中相应项的值为1,否则该位置为0。

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
#对张量中的所有元素求和，会产生一个单元素张量
x.sum()

tensor(66.)

### 2.1.3 广播机制
在某些情况下，即使形状不同，我们仍然可以通过调⽤ ⼴播机制（broadcasting mechanism）来执⾏按元素操作。
这种机制的⼯作⽅式如下：⾸先，通过适当复制元素来扩展⼀个或两个数组，以便在转换之后，两个张量具有相同的形状。其次，对⽣成的数组执⾏按元素操作。在⼤多数情况下，我们将沿着数组中⻓度为1的轴进⾏⼴播，如下例⼦：

In [ ]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [ ]:
#a+b时，两个张量形状不匹配。我们将两个矩阵广播为一个更大的3✖2的张量。
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### 2.1.4 切片和索引
就像在任何其他Python数组中一样，张量中的元素可以通过索引访问。

In [ ]:
#用[-1]选取最后一个元素，[1:3]选择第二个和第三个元素
x[-1], x[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [ ]:
#指定索引将元素写入张量
x[1, 2] = 9
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [ ]:
#如果我们想要为多个元素赋值，我们只需要索引所有的元素，然后为他们赋值。
#[0:2, :]访问的是第一行和第二行，其中“:”代表沿轴1的所有元素。
x[0:2, 1:3] = 11
x

tensor([[12., 11., 11., 12.],
        [12., 11., 11., 12.],
        [ 8.,  9., 10., 11.]])

### 2.1.5 节省内存
运行一些操作可能会导致为新的结果分配内存。例如，如果我们用Y = X + Y，我们将取消引用Y指向的张量，二十指向新分配的内存处的张量。

In [ ]:
before = id(y)
y = x + y
id(y) == before

False

这是不可取的
- 我们不想总是不必要地分配内存
- 如果我们不原地更新参数，其他引用仍然会指向旧的内存位置，这样我们的某些代码可能会无意中引用旧的参数。
执⾏原地操作⾮常简单。我们可以使⽤切⽚表⽰法将操作的结果分配给先前分配的数组，例如`Y[:] = <expression>`。

In [ ]:
Z = torch.zeros_like(y)
print('id(Z):', id(Z))
Z[:] = x + y
print('id(Z):', id(Z))

id(Z): 140507701449968
id(Z): 140507701449968


In [ ]:
#如果在后续计算中没有重复使⽤X，我们也可以使⽤X[:] = X + Y或X += Y来减少操作的内存开销。
before = id(x)
x += y
id(x) == before

True

### 2.1.6 转换为其他Python对象
将深度学习框架定义的张量转换为NumPy张量（ndarray）很容易，反之也同样容易。

In [ ]:
A = x.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [ ]:
#要将⼤⼩为1的张量转换为Python标量，我们可以调⽤item函数或Python的内置函数。
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)